version: "3.8"
services:
  app:
    # TODO replace all "QueueQueen" by dir name 
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: QueueQueen
    command: ["/QueueQueen/docker/app.sh"]
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./queuen.db
        target: /QueueQueen/queuen.db
      - type: bind
        source: ./logs/
        target: /QueueQueen/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`queuen.czertilla.ru`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"

  traefik:
    image: traefik:v3.4
    env_file:
      - .env-non-dev
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
