"""positions_timestamps

Revision ID: 81d332bcdc18
Revises: 54b2808d7648
Create Date: 2024-09-11 18:42:19.345531

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d332bcdc18'
down_revision: Union[str, None] = '54b2808d7648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=str(datetime.now())))
    op.add_column('positions', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'edited_at')
    op.drop_column('positions', 'created_at')
    # ### end Alembic commands ###
